<p>The RGB slider implements the <a href="http://developer.yahoo.com/yui/slider/">YUI Slider Control</a> to create three sliders which, between them, generate an
RGB color.  The background color of each slider is also dynamically modified to reflect the colors that could be
generated by moving a single slider; this affords greater visual feedback to the user and allows her to have a quicker intuitive sense about how to get the desired result.</p>

<p>(<strong>Note:</strong>  YUI also includes a full <a href="http://developer.yahoo.com/yui/colorpicker/">Color Picker Control</a> with a complete set of configurable options.)</p>
