<p>In this example we'll demonstrate the use of all of Paginator's configuration options, including the options added by the bundled UI Components.  Most notably, we'll use the <code>template</code> and <code>pageLabelBuilder</code> options to render the pagination controls in a custom layout with more descriptive page links.  All content in the left column is generated by the Paginator.</p>

