<h3>AutoComplete Control Examples:</h3>

<ul>
<li><a href='/yui/examples/autocomplete/ac_basic_array.html'>Basic Local Data</a></li>
<li><a href='/yui/examples/autocomplete/ac_basic_xhr.html'>Basic Remote Data</a></li>
<li><a href='/yui/examples/autocomplete/ac_xhr_customrequest.html'>Customizing Remote Requests</a></li>
<li><a href='/yui/examples/autocomplete/ac_formatting_proxyless.html'>Custom Formatting, with a Proxyless Remote DataSource</a></li>
<li><a href='/yui/examples/autocomplete/ac_itemselect.html'>Searching Field A, Submitting Field B with itemSelectEvent</a></li>
<li><a href='/yui/examples/autocomplete/ac_combobox.html'>Combo Box</a></li>
<li><a href='/yui/examples/autocomplete/ac_tags_alwaysshow.html'>Tagging Example with alwaysShowContainer</a></li>
<li><a href='/yui/examples/autocomplete/ac_fn_multfields.html'>Custom Function to Search Different Fields at Runtime</a></li>
<li><a href='/yui/examples/autocomplete/ac_ysearch_json.html'>Centering AutoComplete On a Page</a></li>
<li><a href='/yui/examples/autocomplete/ac_ysearch_flat.html'>Subset Matching</a></li>
<li><a href='/yui/examples/autocomplete/ac_flickr_xml.html'>Find Photos on Flickr</a></li>
<li><a href='/yui/examples/autocomplete/ac_customize.html'>Configurations Dashboard</a></li>
<li><a href='/yui/examples/autocomplete/ac_skinning.html'>Skinning Model</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the AutoComplete Control:</h4>

<ul>
<li><a href='/yui/examples/editor/flickr_editor.html'>Flickr Image Search</a> (included with examples for the <a href='/yui/editor/index.html'>Rich Text Editor</a>)</li>
<li><a href='/yui/examples/logger/log_autocomplete.html'>Logger Integration with YUI Components</a> (included with examples for the <a href='/yui/logger/index.html'>Logger Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_autocomplete.html'>Datatable with Autocomplete</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='/yui/layout/index.html'>Layout Manager</a>)</li>
</ul>		
