<h3>Carousel Control Examples:</h3>

<ul>
<li><a href='/yui/examples/carousel/csl_selection.html'>Spotlight example</a></li>
<li><a href='/yui/examples/carousel/csl_circular.html'>Circular Carousel example</a></li>
<li><a href='/yui/examples/carousel/csl_reveal.html'>Partially revealing previous and next items</a></li>
<li><a href='/yui/examples/carousel/csl_imagentext.html'>Using both images and text within an item</a></li>
<li><a href='/yui/examples/carousel/csl_dynload2.html'>Using Ajax for deferred loading of items</a></li>
<li><a href='/yui/examples/carousel/carousel-ariaplugin.html'>Using the Carousel ARIA Plugin</a></li>
</ul>


		
