<h3>DataTable Control Examples:</h3>

<ul>
<li><a href='/yui/examples/datatable/dt_basic.html'>Basic Example</a></li>
<li><a href='/yui/examples/datatable/dt_enhanced.html'>Progressive Enhancement</a></li>
<li><a href='/yui/examples/datatable/dt_formatting.html'>Custom Cell Formatting</a></li>
<li><a href='/yui/examples/datatable/dt_row_coloring.html'>Conditional row coloring</a></li>
<li><a href='/yui/examples/datatable/dt_nestedheaders.html'>Nested Headers</a></li>
<li><a href='/yui/examples/datatable/dt_xhrjson.html'>JSON Data Over XHR</a></li>
<li><a href='/yui/examples/datatable/dt_xhrpostxml.html'>XML Data Over XHR With POST</a></li>
<li><a href='/yui/examples/datatable/dt_xhrtext.html'>Textual Data Over XHR</a></li>
<li><a href='/yui/examples/datatable/dt_xhrlocalxml.html'>Local XML Data</a></li>
<li><a href='/yui/examples/datatable/dt_rowadddelete.html'>Adding and Deleting Rows</a></li>
<li><a href='/yui/examples/datatable/dt_clientpagination.html'>Client-side Pagination</a></li>
<li><a href='/yui/examples/datatable/dt_clientsorting.html'>Client-side Sorting</a></li>
<li><a href='/yui/examples/datatable/dt_dynamicdata.html'>Server-side Pagination and Sorting for Dynamic Data</a></li>
<li><a href='/yui/examples/datatable/dt_fixedscroll.html'>XY-scrolling, Y-scrolling, and X-scrolling</a></li>
<li><a href='/yui/examples/datatable/dt_rowselect.html'>Row Selection</a></li>
<li><a href='/yui/examples/datatable/dt_cellselect.html'>Cell Selection</a></li>
<li><a href='/yui/examples/datatable/dt_cellediting.html'>Inline Cell Editing</a></li>
<li><a href='/yui/examples/datatable/dt_contextmenu.html'>Context Menu Integration</a></li>
<li><a href='/yui/examples/datatable/dt_colshowhide.html'>Showing, Hiding, and Reordering Columns.</a></li>
<li><a href='/yui/examples/datatable/dt_highlighting.html'>Highlighting Cells, Rows, or Columns</a></li>
<li><a href='/yui/examples/datatable/dt_complex.html'>Complex Example of Multiple Features</a></li>
<li><a href='/yui/examples/datatable/dt_autocomplete.html'>Datatable with Autocomplete</a></li>
<li><a href='/yui/examples/datatable/dt_skinning.html'>Skinning Model</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the DataTable Control:</h4>

<ul>
<li><a href='/yui/examples/paginator/pag_configuration.html'>Configuring the Paginator</a> (included with examples for the <a href='/yui/paginator/index.html'>Paginator</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='/yui/layout/index.html'>Layout Manager</a>)</li>
</ul>		
