<h3>DataSource Utility Examples:</h3>

<ul>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the DataSource Utility:</h4>

<ul>
<li><a href='/yui/examples/datatable/dt_rowadddelete.html'>Adding and Deleting Rows</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_basic.html'>Basic Example</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_basic_array.html'>Basic Local Data</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_basic_xhr.html'>Basic Remote Data</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_cellselect.html'>Cell Selection</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_clientpagination.html'>Client-side Pagination</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_clientsorting.html'>Client-side Sorting</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_combobox.html'>Combo Box</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_complex.html'>Complex Example of Multiple Features</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_row_coloring.html'>Conditional row coloring</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_contextmenu.html'>Context Menu Integration</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_formatting.html'>Custom Cell Formatting</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_formatting_proxyless.html'>Custom Formatting, with a Proxyless Remote DataSource</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_fn_multfields.html'>Custom Function to Search Different Fields at Runtime</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_xhr_customrequest.html'>Customizing Remote Requests</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_autocomplete.html'>Datatable with Autocomplete</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_flickr_xml.html'>Find Photos on Flickr</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_highlighting.html'>Highlighting Cells, Rows, or Columns</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_cellediting.html'>Inline Cell Editing</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_xhrjson.html'>JSON Data Over XHR</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_xhrlocalxml.html'>Local XML Data</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_nestedheaders.html'>Nested Headers</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_enhanced.html'>Progressive Enhancement</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_rowselect.html'>Row Selection</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_itemselect.html'>Searching Field A, Submitting Field B with itemSelectEvent</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_dynamicdata.html'>Server-side Pagination and Sorting for Dynamic Data</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_colshowhide.html'>Showing, Hiding, and Reordering Columns.</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_skinning.html'>Skinning Model</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/autocomplete/ac_tags_alwaysshow.html'>Tagging Example with alwaysShowContainer</a> (included with examples for the <a href='/yui/autocomplete/index.html'>AutoComplete Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_xhrtext.html'>Textual Data Over XHR</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_xhrpostxml.html'>XML Data Over XHR With POST</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_fixedscroll.html'>XY-scrolling, Y-scrolling, and X-scrolling</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
</ul>		
