<h3>Drag &amp; Drop Examples:</h3>

<ul>
<li><a href='/yui/examples/dragdrop/dd-basic.html'>Basic Drag and Drop</a></li>
<li><a href='/yui/examples/dragdrop/dd-handles.html'>Using Handles</a></li>
<li><a href='/yui/examples/dragdrop/dd-ontop.html'>Dragged Element on Top</a></li>
<li><a href='/yui/examples/dragdrop/dd-proxy.html'>Using a Proxy Element</a></li>
<li><a href='/yui/examples/dragdrop/dd-reorder.html'>Reordering a List</a></li>
<li><a href='/yui/examples/dragdrop/dd-groups.html'>Using Interaction Groups</a></li>
<li><a href='/yui/examples/dragdrop/dd-circle.html'>Custom Click Validator</a></li>
<li><a href='/yui/examples/dragdrop/dd-region.html'>Staying in a Region</a></li>
<li><a href='/yui/examples/dragdrop/dd-shim.html'>Using the Drag Shim</a></li>
</ul>


		
