<h3>Paginator Examples:</h3>

<ul>
<li><a href='/yui/examples/paginator/pag_getting_started.html'>Getting started with Paginator</a></li>
<li><a href='/yui/examples/paginator/pag_multiple_containers.html'>Rendering controls into multiple containers</a></li>
<li><a href='/yui/examples/paginator/pag_manual_render.html'>Manually rendering Paginator UI Components</a></li>
<li><a href='/yui/examples/paginator/pag_configuration.html'>Configuring the Paginator</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the Paginator:</h4>

<ul>
<li><a href='/yui/examples/datatable/dt_clientpagination.html'>Client-side Pagination</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_dynamicdata.html'>Server-side Pagination and Sorting for Dynamic Data</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
<li><a href='/yui/examples/datatable/dt_complex.html'>Complex Example of Multiple Features</a> (included with examples for the <a href='/yui/datatable/index.html'>DataTable Control</a>)</li>
</ul>		
