<h3>TabView Control Examples:</h3>

<ul>
<li><a href='/yui/examples/tabview/frommarkup.html'>Build from Markup</a></li>
<li><a href='/yui/examples/tabview/fromscript.html'>Build from Script</a></li>
<li><a href='/yui/examples/tabview/addtab.html'>Adding Tabs</a></li>
<li><a href='/yui/examples/tabview/removetab.html'>Removing Tabs</a></li>
<li><a href='/yui/examples/tabview/datasrc.html'>Getting Content from an External Source</a></li>
<li><a href='/yui/examples/tabview/skinning.html'>Skinning TabView</a></li>
<li><a href='/yui/examples/tabview/tabview-ariaplugin.html'>Using the TabView ARIA Plugin</a></li>
</ul>




<h4 id='relatedExamples'>Other YUI Examples That Make Use of the TabView Control:</h4>

<ul>
<li><a href='/yui/examples/editor/tabview_editor.html'>Editor inside a Tabview Control</a> (included with examples for the <a href='/yui/editor/index.html'>Rich Text Editor</a>)</li>
<li><a href='/yui/examples/imageloader/imgloadtabs.html'>ImageLoader with TabView</a> (included with examples for the <a href='/yui/imageloader/index.html'>ImageLoader Utility</a>)</li>
<li><a href='/yui/examples/layout/adv_layout.html'>Complex Application</a> (included with examples for the <a href='/yui/layout/index.html'>Layout Manager</a>)</li>
</ul>		
