<h3>Uploader Control (experimental) Examples:</h3>

<ul>
<li><a href='/yui/examples/uploader/uploader-simple-button.html'>Simple Uploader Example With Button UI</a></li>
<li><a href='/yui/examples/uploader/uploader-advanced-postvars.html'>Advanced Uploader Example With Additional POST Variables and Server Data Return</a></li>
<li><a href='/yui/examples/uploader/uploader-advanced-queue.html'>Advanced Uploader Example With Transparent UI and Automatic Queue Management</a></li>
</ul>


		
